# Day-6
NPM and Yarn are package managers that help to manage a project's dependencies 
## dependency
a piece of code that is required to make the project work properly. We need them because managing the project's dependencies is a difficult tas

# NPM
It is a package manager for the JavaScript programming language. It is the default package manager for the JavaScript runtime environment Node.js.

## YARN
It stands for Yet Another Resource Negotiator and it is a package manager just like npm. It was developed by Facebook and is now open-source. 

npm: npm is installed with Node automatically.
yarn: To install yarn npm have to be installed.

npm: NPM generates a ‘package-lock.json’ file. 
yarn: Yarn generates a ‘yarn.lock’ file

# async 
The keyword async before a function makes the function return a promise
Await Syntax
The await keyword can only be used inside an async function.

The await keyword makes the function pause the execution and wait for a resolved promise before it continues:


The DOM tree, or Document Object Model tree, is a programming interface that represents an HTML or XML document as a hierarchical structure of interconnected objects, known as nodes.

When a web page is loaded, the browser creates a Document Object Model of the page.

The HTML DOM model is constructed as a tree of Objects

With the object model, JavaScript gets all the power it needs to create dynamic HTML:

JavaScript can change all the HTML elements in the page

JavaScript can change all the HTML attributes in the page

JavaScript can change all the CSS styles in the page

JavaScript can remove existing HTML elements and attributes

JavaScript can add new HTML elements and attributes

JavaScript can react to all existing HTML events in the page

JavaScript can create new HTML events in the page

# Try and catch - error handling
The try statement defines a code block to run (to try).

The catch statement defines a code block to handle any error.

The finally statement defines a code block to run regardless of the result.

The throw statement defines a custom error.

The try statement allows you to define a block of code to be tested for errors while it is being executed.

The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.

### errors

Error Name	Description
`EvalError`	An error has occurred in the eval() function
`RangeError`	A number "out of range" has occurred
`ReferenceError`	An illegal reference has occurred
`SyntaxError`	A syntax error has occurred
`TypeError`	A type error has occurred
`URIError`	An error in encodeURI() has occurred
